version: '3.8'
services:

  qkmath-server:
    build: .
    image: jaironlanda/math-gen
    command: uvicorn main:app --reload --workers 2 --host 0.0.0.0 --port 8001
    volumes:
      - ./:/app
    ports:
      - 8001:8001
    restart: always