name: NewbAPI Math-gen API build image

on:
  # Build and push Docker images *only* for releases.
  push:
    branches:       
      - build # branch to build docker image and push to docker hub

jobs:
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      APP_VERSION: 0.1-alpha

    steps:
      # checkout
      - name: Check out the repo
        id: checkout
        uses: actions/checkout@v2
      
      # recomend by docker
      - name: Set up Docker Buildx
        id: buidx
        uses: docker/setup-buildx-action@v2
      
      # login to docker hub
      - name: Login Docker Hub
        id: docker-auth
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: jaironlanda/newbapi-math-gen:1.0
      
      - name: Slack Noti
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()