name: Deploy math-gen-api

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      USER_AUTH : ${{ secrets.USER_AUTH }}

    steps:
      - name: Login VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export "${{ secrets.USER_AUTH }}" | sudo -S
            sudo docker compose -f docker-compose.yml pull ${{ secrets.COINTAINER_NAME }} && \
            sudo docker compose -f docker-compose.yml up ${{secrets.COINTAINER_NAME}} -d && \
            sudo docker image prune -f
    
      - name: Slack Noti
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()